apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: tmkinidx5-python-gitops
  description: This is GitOps manifest for tmkinidx5-python   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-name: tmkinidx5-python
    janus-idp.io/tekton: tmkinidx5-python 
    backstage.io/kubernetes-id: tmkinidx5-python 
    backstage.io/techdocs-ref: dir:. 
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:tmkinidx5-python
