apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: tmkinidx5-python
  janus-idp.io/tekton: tmkinidx5-python
  backstage.io/kubernetes-id: tmkinidx5-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: tmkinidx5-python
resources:
- deployment.yaml
- route.yaml
- service.yaml
